version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    working_directory: /tmp/paratii-mediaplayer
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn run build
  deploy:
    docker:
      - image: circleci/node:8.9.1
    working_directory: /tmp/paratii-mediaplayer
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
