version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    working_directory: /tmp/paratii-mediaplayer
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn run build
      - persist_to_workspace:
          root: /tmp/paratii-mediaplayer
          paths:
            - build/
            - package.json
  deploy:
    docker:
      - image: circleci/node:8.9.1
    working_directory: /tmp/paratii-mediaplayer
    steps:
      - attach_workspace:
          at: /tmp/paratii-mediaplayer
      - run:
          name: Deploy to npm
          command: npm publish
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
